### ISSUE TITLE
DTrace pretty printer for UUIDs

### ISSUE THREAD

**Issue by rwatson** [cadets/freebsd#15]
It would be nice if there were a convenient (even automatic?) way to print UUID information in the preferred UID string format (per https://www.ietf.org/rfc/rfc4122.txt) from a D script. Today, printing a ```struct uuid``` simply generates a sequence of bytes, which is OK, but probably not as good as printing it properly. I'm not sure if D should simply know how to print UUIDs the way it knows how to print integers, strings, etc, or if some explicit syntax should be required. I find myself gently leaning towards the former, as having ```trace(foo->uuid)``` automatically format as a UUID would be easiest for the user.

**Comment by rwatson** [comment]
(Assigned to @arunthomas since he is pursuing this!)

**Comment by arunthomas** [comment]
Commit fcf132cad66d20837fd18a03d1ae465f5ec2fe5f adds a new format specifier (%U) for uuids. We are currently duplicating code from kern_uuid.c and I haven't implemented pfcheck_uuid yet, but it mostly seems to work.

I would like to support for `trace(foo->uuid)` in the future, but I wasn't quite sure how to teach D about new types.

**Comment by rwatson** [comment]
Seems "closed enough" for our purposes, so closing this issue.
