### ISSUE TITLE
Postgres DTrace provider doesn't work

### ISSUE THREAD

**Issue by arunthomas** [cadets/freebsd#4]
I attempted to build postgres from ports with dtrace build support enabled. The build succeeded, but the DTrace provider did not appear to be built. If I build postgres from the upstream git repository with '--enable-dtrace', the DTrace provider does indeed work.

I vaguely remember seeing some warning about duplicate object files when building the port, but I didn't have a chance to investigate further.

Amanda reports success with postgres 9.3 (from ports) and its DTrace provider. It's certainly possible I did something wrong or maybe there's an issue with the postgres 9.5 port.

**Comment by gvnn3** [comment]
It looks like going back to 9.2 that the DTrace flag is set in the port, but that is it NOT set in the package.  Installing the package and then running:

pkg info --full postgresql95-server

showed that DTRACE was off, but then installing the port allowed me to turn it on in the config dialog. 

It's very likely that you missed that step, using the dialog.

**Comment by arunthomas** [comment]
I did enable dtrace in the config step, but I'm guessing I did something else wrong. Thanks for looking into this.

**Comment by No9** [comment]
Quick note as I just stumbled into this issue and this came up in the search results
I enabled dtrace at start in __/boot/loader.conf__
`dtraceall_load="YES"`

Then I added postgresql user access to wheel.
`pw groupmod wheel -m postgres`

Taken from https://www.postgresql.org/message-id/CAG1_KcAhqf7PXy0FH%2BgX%3Dv%2BLHP4_cQJ9xM83Rqb%3Ds5iLu1vdXw@mail.gmail.com
