### ISSUE TITLE
su fails when auditd enabled (cadets branch)

### ISSUE THREAD

**Issue by arunthomas** [cadets/freebsd#46]
I am seeing an Audit issue that prevents logging in from an ipmi console and running 'su'.

Here's the relevant snippet from the logs:

~~~
Aug  2 19:15:58 blackmarsh2 auditd[1771]: Auditing disabled
Aug  2 19:15:58 blackmarsh2 auditd[1771]: Auditing enabled
Aug  2 19:15:58 blackmarsh2 auditd[1771]: New audit file is /var/audit/20160802191558.not_terminated
Aug  2 19:15:58 blackmarsh2 auditd[1771]: auditd_gen_record(AUE_audit_startup) could not close audit record: Invalid argument
Aug  2 19:15:58 blackmarsh2 auditd[1771]: audit_control(5) may be missing 'host:' field
Aug  2 19:18:58 blackmarsh2 su: audit: record not committed
Aug  2 19:19:18 blackmarsh2 su: audit: record not committed
~~~

Our audit configuration is here:

~~~
dir:/var/audit
dist:off
flags:
naflags:lo
policy:cnt
qsize:10000
minfree:5
filesz:2M
expire-after:10M
~~~~

If I disable auditing (`service auditd stop`), `su` and login work again. Likely a configuration error?

**Comment by rwatson** [comment]
Is this something that happens intermittently or spontaneously, or something that always happens with the above configuration?

**Comment by arunthomas** [comment]
It seems to happen every time I start/restart auditd.

**Comment by rwatson** [comment]
Hmm. When I install this ```/etc/security/audit_control```, and stop + start ```auditd```, I am still able to SSH in and ```su(8)```. I do not see the messages above about being unable to audit restart of the daemon either. Are you logging in via SSH, or on the console?

**Comment by arunthomas** [comment]
It appears SSH continues to work. I am not able to log in from the console, and I am not able to su. 

I'll ask @trombonehero  to create an account for you on the MUN machines.

**Comment by rwatson** [comment]
It looks like the issue relates to the ```qsize``` value in ```audit_control``` -- when I comment out that line, ```audit(2)``` stops returning ```EINVAL```. It looks like the kernel is ending up with ```audit_qctrl.aq_bufsz``` of 0, rejecting all user-generated audit records. I'll investigate further, but you should be able to get up and running again properly with that configuration line commented out.

**Comment by rwatson** [comment]
Further investigation suggests that the issue is with ed98be5180ac28a33129f63fc9b659051b64bcb3, in which the ```au_qctrl``` argument used to set the audit-queue depth limit starts with a zeroed structure, rather than one first retrieved from the kernel, which improperly zeroes other kernel audit parameters. I will try fixing that and see what happens!

**Comment by rwatson** [comment]
Believed fixed, please confirm.
