### ISSUE TITLE
DTaudit: possible aue_pipe issue

### ISSUE THREAD

**Issue by arunthomas** [cadets/freebsd#48]
In the engagement traces, the event for `aue_pipe` has subj, thr, ret_obj1, ret_obj2 UUIDs and they are all the same. This is an issue as postgres used pipes internally.

**Comment by rwatson** [comment]
Hum. I was sure I had tested this explicitly to ensure we had unique UUIDs for each endpoint and that they were distinct from the subject UUID -- could you include an excerpt of the problematic output and pointer to the specific version of the capture script used in the engagement?

**Comment by arunthomas** [comment]
Just checked with Lucian again. This was a misinterpretation of the traces. Only ret_obj1 and ret_obj2 UUIDs are the same, but that's expected behavior.

For OPUS analysis, it would be helpful if we captured the fds or separate UUIDs on the read and write ends of the pipe (#50)

**Comment by lc525** [comment]
It's my bad for reporting things slightly incorrectly. We only did an eye-comparison of UUIDs and they all looked the same. However, only ret_obj1 and ret_obj2 are the same.

Here's the excerpt from the trace:
```
{"event": "audit:event:aue_pipe:", "time": 1472591587188244438, "pid": 2675, "ppid": 927, "tid": 100181, "uid": 70, "exec": "postgres", "subjprocuuid": "8c0a6d2b-6ef6-11e6-a186-9d48423d0e3e", "subjthruuid": "543d8422-6ee8-11e6-a186-9d48423d0e3e", "ret_objuuid1": "8c0a8cfe-6ef6-11e6-a186-9d48423d0e3e", "ret_objuuid2": "8c0a8cfe-6ef6-11e6-a186-9d48423d0e3e", "retval": 0}
, {"event": "audit:event:aue_fcntl:", "time": 1472591587188244438, "pid": 2675, "ppid": 927, "tid": 100181, "uid": 70, "exec": "postgres", "subjprocuuid": "8c0a6d2b-6ef6-11e6-a186-9d48423d0e3e", "subjthruuid": "543d8422-6ee8-11e6-a186-9d48423d0e3e", "arg_objuuid1": "8c0a8cfe-6ef6-11e6-a186-9d48423d0e3e", "retval": 0}
```

**Comment by lc525** [comment]
So on the first event, a pipe is created and we have the same uuid for both the read and the write endpoints.

Then, one of the endpoints (we get the same uuid used as an arg_obj) is used in a fcntl (likely, it sets something like a CLOEXEC on one of the file descriptors in the trace).

Then, the uuid never apears again in the trace.

**Comment by lc525** [comment]
@arunthomas Is having the same UUID for both ends of the pipe expected behavior though? Robert's initial comment sort of implies that that is not the case? 

OPUS would be happy with one UUID for the pipe and two file descriptors for its ends.

**Comment by arunthomas** [comment]
@lc525 You're right. I skimmed Robert's response too quickly.

@rwatson, this is the script we are using for the engagement:
https://github.com/cadets/dtrace-scripts/blob/master/audit.d

**Comment by rwatson** [comment]
In my first pass at pipe UUID support, I did use the same UUID for both end points. I later revised that to use different UUIDs for exactly the reason cited -- they are effectively different kernel objects. However, I wonder if that latter change ended up getting propagated to all pertinent branches. When I get back to my hotel, I'll take a look and see if I failed to push the change -- or if it ended up stuck in a branch and was not used generating the trace.

**Comment by rwatson** [comment]
Hmm. So, in this simple test on the audit_uuid branch, I see the behaviour I expect:
```
root@lemongrass-freebsd64:/home/robert # dtrace -n 'audit:event:aue_pipe:commit  { trace(args[1]->ar_ret_objuuid1); trace(args[1]->ar_ret_objuuid2); }'
dtrace: description 'audit:event:aue_pipe:commit  ' matched 1 probe
CPU     ID                    FUNCTION:NAME
  1  60464                  aue_pipe:commit 
             0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
         0: 76 22 06 cc ec 8e e6 11 86 7e 00 25 4b 9d 9c b4  v".......~.%K...

             0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
         0: 7a 22 06 cc ec 8e e6 11 86 7e 00 25 4b 9d 9c b4  z".......~.%K...
```

In a separate window, I simply ran ```echo | cat``` to trigger creation of the pipe.

Notice a small difference in byte 0 of the UUID between the first and second return UUIDs.

It would be useful if you could run the above DTrace command and see whether you see consistent results with the problem you see with the more complex script, or the output I see. If the former, then perhaps there is a missing merge in a CADETS branch (or some other not-yet-understood bug); if the latter, perhaps a bug in the script? (Do read the hex bit, not the presumed ASCII string, as the difference in those bits isn't visible in the text representation.)

**Comment by arunthomas** [comment]
Thanks for looking into this, Robert. There is a bug in the audit.d script. Sorry for not noticing this sooner.

I've fixed the script and verified that we see different UUIDs on each pipe endpoint.
