### ISSUE TITLE
CADETS trace files are invalid json

### ISSUE THREAD

**Issue by lc525** [cadets/freebsd#52]
A lot of \0 characters appear in the json CADETS trace files, because of dtrace’s %S printf format specifier. This means most json parsers just give up. This is a known issue but perhaps it's worth fixing?

It is particularly problematic in OPUS as I'm trying to incrementally read the traces directly from their compressed form (the .xz)

**Comment by arunthomas** [comment]
This was fixed in 6117022193af843d3aa73b4e2e70f505993de85d.
